name: Build and Release

on:
  push:
    branches: ["project"]
    tags:
      - 'v*'
  pull_request:
    branches: ["project"]

# ВОТ ЭТОТ БЛОК НАДО ДОБАВИТЬ:
permissions:
  contents: write

jobs:
  build:
    name: Build Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build cmdflow
        working-directory: cmdflow
        run: cargo build --release --verbose

      - name: Run tests
        working-directory: cmdflow
        run: cargo test --verbose

      - name: Check cmdflow runs
        working-directory: cmdflow
        run: ./target/release/cmdflow --version

      - name: Prepare asset
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp cmdflow/target/release/cmdflow ./cmdflow-linux-x86_64

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: cmdflow-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
